---
apiVersion: "kustomize.config.k8s.io/v1beta1"
kind: "Kustomization"
namePrefix: "lecture2gether-"
commonLabels:
  app: "lecture2gether"
resources:
  - "./k8s/deployment.yml"
  - "./k8s/service.yml"
configMapGenerator:
  - name: "backend"
  - name: "frontend"
    files:
      - "settings.json=./docker/settings.json"
