---
apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "deployment"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "NOT_SET"
  template:
    metadata:
      labels:
        app: "NOT_SET"
    spec:
      containers:
        - image: "docker.io/thenerdful8/lecture2gether"
          name: "main"
          ports:
            - name: "http"
              containerPort: 8000
