---
apiVersion: "v1"
kind: "Service"
metadata:
  name: "service"
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "5000"
spec:
  type: "ClusterIP"
  selector:
    app: "NOT_SET"
  ports:
    - name: "http"
      port: 80
      targetPort: "http"
    - name: "metrics"
      port: 5000
      targetPort: "metrics"

