[tool.poetry]
name = "lecture2gether_flask"
version = "0.1.0"
description = "Flask backend for the lecture2gether service"
authors = ["Florian <florian@flova.de>"]
license = "MIT"

[tool.poetry.dependencies]
python = "3.8.2"
flask = "^1.1.2"
flask-restful = "^0.3.8"
pyOpenSSL = "^19.1.0"
secrets = "^1.0.2"
requests = "^2.23.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
