name: Flask CI

on: [push]

jobs:
  pytest:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: shogo82148/actions-setup-redis@v1
        with:
          redis-version: '5.x'
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry install --no-root
        working-directory: lecture2gether_flask
      - name: Run Tests
        run: |
          poetry run nosetests test.py
        env:
          L2G_TEST_PASSWD: ${{ secrets.L2G_TEST_PASSWD }}
          GOOGLE_YOUTUBE_API_KEY: ${{ secrets.GOOGLE_YOUTUBE_API_KEY }}
          GOOGLE_DRIVE_API_KEY: ${{ secrets.GOOGLE_DRIVE_API_KEY }}
        working-directory: lecture2gether_flask
